// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Gender             pgtype.Text        `json:"gender"`
	GenderProbability  pgtype.Float8      `json:"gender_probability"`
	Age                pgtype.Int4        `json:"age"`
	AgeGroup           pgtype.Text        `json:"age_group"`
	CountryID          pgtype.Text        `json:"country_id"`
	CountryProbability pgtype.Float8      `json:"country_probability"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CountryName        pgtype.Text        `json:"country_name"`
}
