// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProfilesAdvanced = `-- name: CountProfilesAdvanced :one
SELECT COUNT(*) FROM profiles
WHERE
    (CARDINALITY($1::text[]) = 0 OR gender = ANY($1))
AND ($2::text = '' OR age_group = $2)
AND ($3::text = '' OR country_id ILIKE $3)
AND ($4::text = '' OR country_name ILIKE $4)
AND ($5::int = 0 OR age >= $5)
AND ($6::int = 0 OR age <= $6)
AND ($7::int = 0 OR age = $7)
AND ($8::float = 0 OR gender_probability >= $8)
AND ($9::float = 0 OR country_probability >= $9)
`

type CountProfilesAdvancedParams struct {
	Genders        []string `json:"genders"`
	AgeGroup       string   `json:"age_group"`
	CountryID      string   `json:"country_id"`
	CountryName    string   `json:"country_name"`
	MinAge         int32    `json:"min_age"`
	MaxAge         int32    `json:"max_age"`
	ExactAge       int32    `json:"exact_age"`
	MinGenderProb  float64  `json:"min_gender_prob"`
	MinCountryProb float64  `json:"min_country_prob"`
}

func (q *Queries) CountProfilesAdvanced(ctx context.Context, arg CountProfilesAdvancedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProfilesAdvanced,
		arg.Genders,
		arg.AgeGroup,
		arg.CountryID,
		arg.CountryName,
		arg.MinAge,
		arg.MaxAge,
		arg.ExactAge,
		arg.MinGenderProb,
		arg.MinCountryProb,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    id, name, gender, gender_probability, age, age_group, country_id, country_name, country_probability
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, gender, gender_probability, age, age_group, country_id, country_probability, created_at, country_name
`

type CreateProfileParams struct {
	ID                 pgtype.UUID   `json:"id"`
	Name               string        `json:"name"`
	Gender             pgtype.Text   `json:"gender"`
	GenderProbability  pgtype.Float8 `json:"gender_probability"`
	Age                pgtype.Int4   `json:"age"`
	AgeGroup           pgtype.Text   `json:"age_group"`
	CountryID          pgtype.Text   `json:"country_id"`
	CountryName        pgtype.Text   `json:"country_name"`
	CountryProbability pgtype.Float8 `json:"country_probability"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.GenderProbability,
		arg.Age,
		arg.AgeGroup,
		arg.CountryID,
		arg.CountryName,
		arg.CountryProbability,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.GenderProbability,
		&i.Age,
		&i.AgeGroup,
		&i.CountryID,
		&i.CountryProbability,
		&i.CreatedAt,
		&i.CountryName,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, gender, gender_probability, age, age_group, country_id, country_probability, created_at, country_name FROM profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.GenderProbability,
		&i.Age,
		&i.AgeGroup,
		&i.CountryID,
		&i.CountryProbability,
		&i.CreatedAt,
		&i.CountryName,
	)
	return i, err
}

const getProfileByName = `-- name: GetProfileByName :one
SELECT id, name, gender, gender_probability, age, age_group, country_id, country_probability, created_at, country_name FROM profiles
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProfileByName(ctx context.Context, name string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByName, name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.GenderProbability,
		&i.Age,
		&i.AgeGroup,
		&i.CountryID,
		&i.CountryProbability,
		&i.CreatedAt,
		&i.CountryName,
	)
	return i, err
}

const listProfilesAdvanced = `-- name: ListProfilesAdvanced :many
SELECT id, name, gender, gender_probability, age, age_group, country_id, country_probability, created_at, country_name FROM profiles
WHERE
    (CARDINALITY($1::text[]) = 0 OR gender = ANY($1))
AND ($2::text = '' OR age_group = $2)
AND ($3::text = '' OR country_id ILIKE $3)
AND ($4::text = '' OR country_name ILIKE $4)
AND ($5::int = 0 OR age >= $5)
AND ($6::int = 0 OR age <= $6)
AND ($7::int = 0 OR age = $7)
AND ($8::float = 0 OR gender_probability >= $8)
AND ($9::float = 0 OR country_probability >= $9)
ORDER BY 
    CASE WHEN $10::text = 'age' AND $11::text = 'asc' THEN age END ASC,
    CASE WHEN $10::text = 'age' AND $11::text = 'desc' THEN age END DESC,
    CASE WHEN $10::text = 'created_at' AND $11::text = 'asc' THEN created_at END ASC,
    CASE WHEN $10::text = 'created_at' AND $11::text = 'desc' THEN created_at END DESC,
    CASE WHEN $10::text = 'gender_probability' AND $11::text = 'asc' THEN gender_probability END ASC,
    CASE WHEN $10::text = 'gender_probability' AND $11::text = 'desc' THEN gender_probability END DESC,
    created_at DESC
LIMIT $13
OFFSET $12
`

type ListProfilesAdvancedParams struct {
	Genders        []string `json:"genders"`
	AgeGroup       string   `json:"age_group"`
	CountryID      string   `json:"country_id"`
	CountryName    string   `json:"country_name"`
	MinAge         int32    `json:"min_age"`
	MaxAge         int32    `json:"max_age"`
	ExactAge       int32    `json:"exact_age"`
	MinGenderProb  float64  `json:"min_gender_prob"`
	MinCountryProb float64  `json:"min_country_prob"`
	SortBy         string   `json:"sort_by"`
	SortDirection  string   `json:"sort_direction"`
	OffsetVal      int32    `json:"offset_val"`
	LimitVal       int32    `json:"limit_val"`
}

func (q *Queries) ListProfilesAdvanced(ctx context.Context, arg ListProfilesAdvancedParams) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfilesAdvanced,
		arg.Genders,
		arg.AgeGroup,
		arg.CountryID,
		arg.CountryName,
		arg.MinAge,
		arg.MaxAge,
		arg.ExactAge,
		arg.MinGenderProb,
		arg.MinCountryProb,
		arg.SortBy,
		arg.SortDirection,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.GenderProbability,
			&i.Age,
			&i.AgeGroup,
			&i.CountryID,
			&i.CountryProbability,
			&i.CreatedAt,
			&i.CountryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO profiles (
    id, name, gender, gender_probability, age, age_group, country_id, country_name, country_probability
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (name) DO UPDATE SET
    gender = EXCLUDED.gender,
    gender_probability = EXCLUDED.gender_probability,
    age = EXCLUDED.age,
    age_group = EXCLUDED.age_group,
    country_id = EXCLUDED.country_id,
    country_name = EXCLUDED.country_name,
    country_probability = EXCLUDED.country_probability
`

type UpsertUserParams struct {
	ID                 pgtype.UUID   `json:"id"`
	Name               string        `json:"name"`
	Gender             pgtype.Text   `json:"gender"`
	GenderProbability  pgtype.Float8 `json:"gender_probability"`
	Age                pgtype.Int4   `json:"age"`
	AgeGroup           pgtype.Text   `json:"age_group"`
	CountryID          pgtype.Text   `json:"country_id"`
	CountryName        pgtype.Text   `json:"country_name"`
	CountryProbability pgtype.Float8 `json:"country_probability"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.GenderProbability,
		arg.Age,
		arg.AgeGroup,
		arg.CountryID,
		arg.CountryName,
		arg.CountryProbability,
	)
	return err
}
