// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, github_id, username, email, avatar_url, role, is_active, last_login_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, github_id, username, email, avatar_url, role, is_active, last_login_at, created_at, refresh_token
`

type CreateUserParams struct {
	ID          pgtype.UUID        `json:"id"`
	GithubID    string             `json:"github_id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Role        string             `json:"role"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.GithubID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
		arg.Role,
		arg.IsActive,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.RefreshToken,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, github_id, username, email, avatar_url, role, is_active, last_login_at, created_at, refresh_token FROM users
WHERE github_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.RefreshToken,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, username, email, avatar_url, role, is_active, last_login_at, created_at, refresh_token FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.RefreshToken,
	)
	return i, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT id, github_id, username, email, avatar_url, role, is_active, last_login_at, created_at, refresh_token FROM users
WHERE refresh_token = $1 LIMIT 1
`

func (q *Queries) GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByRefreshToken, refreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.RefreshToken,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE users
SET refresh_token = $2
WHERE id = $1
`

type UpdateRefreshTokenParams struct {
	ID           pgtype.UUID `json:"id"`
	RefreshToken pgtype.Text `json:"refresh_token"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateRefreshToken, arg.ID, arg.RefreshToken)
	return err
}
